name: Deploy to swarm

on:
  push


env:
  REMOTE_USER: git
  REMOTE_HOST: mydomain.com
  REGISTRY_HOST: ghcr.io
  APP_NAME: my-fancy-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        run: echo "::set-env name=IMAGE_TAG::${{ github.repository_owner }}/${{ env.APP_NAME }}"

      - name: Build and push to container registry
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          repository: ${{ env.IMAGE_TAG }}
          tags: latest

      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          git fetch --unshallow
          git remote add swarm $REMOTE_USER@$REMOTE_HOST:$APP_NAME
          GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
          git push -u swarm master --force
