version: '3.7'

services:
  web:
    image: ghcr.io/melscoop/my-fancy-app
    secrets:
      - github-registry-secrets
    networks:
      - melscoop-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - nope

secrets:
  github-registry-secrets:
    external: true

networks:
  traefik-public:
    external: true
